version: '3.8'

services:
  notas_do_deep_database:
    image: postgres:latest
    container_name: database_containner
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/db
    environment:
      - POSTGRES_DB=notas_do_deep_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - projetoII_network

  db_pgadmin:
    image: dpage/pgadmin4
    container_name: db_pgadmin4
    restart: always
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - projetoII_network
    depends_on:
      - notas_do_deep_database

networks:
  projetoII_network:
    driver: bridge
